import nmap3
nmap = nmap3.Nmap()
k=input("hote ?")
results = nmap.scan_top_ports(k)
print(results)
k=input("dns ?")
results = nmap.nmap_dns_brute_script(k)
print(results)
k=input("hote ?")
results = nmap.nmap_list_scan(k)
print(results)
k=input("hote ?")
results = nmap.nmap_os_detection(k)
print(results)
k=input("hote ?")
results = nmap.nmap_subnet_scan(k)
print(results)
k=input("hote ?")
result = nmap.nmap_tcp_scan(k)
print(results)


